### ISSUE TITLE
關於Project3問題請教

### ISSUE THREAD

**Issue by vincentzhang6130** [OuTingYun/Linux#1]
你好，我是中央資工的學生，我最近在複習Linux的作業，無意間看到你的這份筆記，覺得寫得很好:thumbsup:
所以我有試了Project3 你計算`wq_count`的方法，但不能理解為什麼在 `q2.c` 中執行了getchar & printf 不是讓 wq_count ++兩次變為2，而是各為1 呢? 
想說這個process不應該要進waiting queue 等待I/O完成兩次嗎?  希望你能撥冗回答，謝謝!

**Comment by vincentzhang6130** [comment]
抱歉打擾:pray:，我後來把 `q2.c` 打印的迴圈設更大後wq_count確實有增加，發現前面的問題只是因為迴圈跑的時間太短，process不需進wq造成。

**Comment by elite3312** [comment]
> 抱歉打擾🙏，我後來把 `q2.c` 打印的迴圈設更大後wq_count確實有增加，發現前面的問題只是因為迴圈跑的時間太短，process不需進wq造成。

還敢質疑女神啊XD
